/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.8.2
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IMonitArgs {
    memory?: number;
    cpu?: number;
}
export class Monit {
    public memory?: number;
    public cpu?: number;
    constructor(args?: IMonitArgs) {
        if (args != null && args.memory != null) {
            this.memory = args.memory;
        }
        if (args != null && args.cpu != null) {
            this.cpu = args.cpu;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("Monit");
        if (this.memory != null) {
            output.writeFieldBegin("memory", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.memory);
            output.writeFieldEnd();
        }
        if (this.cpu != null) {
            output.writeFieldBegin("cpu", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.cpu);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): Monit {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.memory = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.cpu = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new Monit(_args);
    }
}
