/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.8.2
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 from "node-int64";
import * as thrift from "thrift";
export interface IMonitArgs {
    memory?: number | Int64;
    cpu?: number | Int64;
}
export class Monit {
    public memory?: Int64;
    public cpu?: Int64;
    constructor(args?: IMonitArgs) {
        if (args != null && args.memory != null) {
            if (typeof args.memory === "number") {
                this.memory = new Int64(args.memory);
            }
            else {
                this.memory = args.memory;
            }
        }
        if (args != null && args.cpu != null) {
            if (typeof args.cpu === "number") {
                this.cpu = new Int64(args.cpu);
            }
            else {
                this.cpu = args.cpu;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("Monit");
        if (this.memory != null) {
            output.writeFieldBegin("memory", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.memory);
            output.writeFieldEnd();
        }
        if (this.cpu != null) {
            output.writeFieldBegin("cpu", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.cpu);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): Monit {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.memory = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.cpu = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new Monit(_args);
    }
}
